fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Api\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: Api\UserBundle\Form\Type\RegistrationFormType
            name: registration_form
            validation_groups: [ApiRegistration]
    profile:
        form:
            type: Api\UserBundle\Form\Type\ProfileFormType
            name: profile_form
            validation_groups: [ApiProfile]