services:
#    api_bookmark.example:
#        class: Api\BookmarkBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    serializer_listener.bookmark_folder:
        class: Api\BookmarkBundle\Serializer\Listener\BookmarkFolderListener
        tags:
            - { name: jms_serializer.event_subscriber }