services:
#    api_user.example:
#        class: Api\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    serializer_listener.user:
        class: Api\UserBundle\Serializer\Listener\UserListener
        tags:
            - { name: jms_serializer.event_subscriber }