# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: emailCanonical
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "ApiRegistration", "ApiProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "ApiRegistration", "ApiProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "ApiRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "ApiRegistration", "ApiProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "ApiRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "ApiRegistration", "ApiProfile", "ResetPassword", "ChangePassword"]